[package]
name = "stm32-playground"
version = "0.1.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]

[dependencies]
cortex-m-rt = "*"
cortex-m-rtfm = "*"
f3 = "*"

[profile]
[profile.release]
debug = true
lto = true
